#pragma once
#define G3DTZ_MESSAGE "Generated by g3DTZ v2.0 - by guard3"

bool ExtractModelInfoAndStuff();
bool ExtractIPLs();
bool ExtractObjectData();
bool ExtractPedStats();
bool ExtractAnimations();
bool ExtractSurfaceTable();
bool ExtractTimeCycle();
bool ExtractPedGroups();
bool ExtractWeaponInfo();
bool ExtractDIRs();
bool ExtractParticle();
bool ExtractWaterLevel();